language: python
matrix:
  include:
  - env: TOXENV=mypy
    python: 3.8
  - env: TOXENV=flake8
    python: 3.8
  - env: TOXENV=py37
    python: 3.7
  - env: TOXENV=py38
    python: 3.8
install:
- pip install tox
script:
- tox
deploy:
  provider: pypi
  username: __token__
  password:
    secure: ekjZPJmE5fyA709niEaEqu36+tnJ+omV4zDNIw0WjMmRni1yXOyCJOFkVpJqliJaGwbQ0VfuRva5yw5aBFbAD6D2leVN4CYLOiqkYdrlKyr8PZYugMuub2X/7eqKRgfU8GF/xHsVQSCs1Pf6za+RMU/cwViQq+jRdsrKknhCo21jus5cRfnKEk30nKufsP9UbxZ1Rsf5T5S11ET/gPF8rL56+SbaLDn1N2WHdmfLP5lFzPMNhudD7rS6dLDVTsj2yFDwyZGkXE+0TbZTxUXaE0cKmKjC0oF4LVryXamdMVhavUUgTvZRt0Y5nUBFFnY3X/mLGfoJ+1Lu4fHggJ1tU0TPPOlGJ6OtBfI9pE2G1f+08dRSFjX2zxVivSSGy/omllXAPXLR2JWh3LWj/RksoteXqZsl04/CLMbuSsc7LVZ3Q5CGElhHFSBdh3RjrIHESARUzdJLz/IYy/x6nMaMIFQe0VtrdTqkLopA/eKk9Q8OWghn4lbqt9QkuIW2UJql1KUw8AiUUhPQe0cEm/xY5GjfBC5HhjOuEggHijpnzs+qyU+TYDgNIz5gBc2d/x5vhr+Piu33Riqj0z4ch81ZJ0186s7AG8zkguyGxq8k2MkzImyWh2rOV7xBin7vWff+UCNG7egrCp07C7tbS+KBOlX36anJDEtrpnuevGjFVKA=
  on:
    tags: true
  skip_existing: true
